### ISSUE TITLE
Not receiving thumbs up songs

### ISSUE THREAD

**Issue by eebs323** [donnierayjones/pandordio-chrome#1]
Hi Donnie,

After debugging the problem, I get a "Uncaught ReferenceError: webkitNotifications is not defined" error in line 7 in *background.js. This line includes: 

var notification = webkitNotifications.createNotification(
'icon48.png', 
title, 
text);

I've googled this problem and it might be because webKitNotifications aka rich notifications is deprecated and you should now use HTML5 notifications instead. Can you please update your code to fix this problem? I would greatly appreciate it!

Thank you,
-Eli

**Comment by donnierayjones** [comment]
Hey Eli,

Sorry about this. I'm no longer using this extension myself. I'll take a look this evening and see if I can get a fix for it - hopefully this is the only thing that no longer works.

**Comment by donnierayjones** [comment]
This should be fixed now in version 0.1.0. Thanks for letting me know.
